---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name rxresume-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: rxresume
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .pg_user }}"
        INIT_POSTGRES_PASS: "{{ .pg_pass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pg_pass }}"
        DATABASE_URL: "{{ .db_url }}"
        STORAGE_BUCKET: rxresume
        STORAGE_ENDPOINT: "{{ .endpoint }}"
        STORAGE_REGION: ""
        STORAGE_ACCESS_KEY: "{{ .access_key }}"
        STORAGE_SECRET_KEY: "{{ .secret_key }}"
        STORAGE_USE_SSL: "true"
        STORAGE_PORT: "443"
        GOOGLE_CLIENT_ID: google_client_id
        GOOGLE_CLIENT_SECRET: google_client_secret
        GOOGLE_CALLBACK_URL: http://localhost:3000/api/auth/google/callback
        GITHUB_CLIENT_ID: github_client_id
        GITHUB_CLIENT_SECRET: github_client_secret
        GITHUB_CALLBACK_URL: http://localhost:3000/api/auth/github/callback
  dataFrom:
  - extract:
      key: rxresume
  - extract:
      key: minio
  - extract:
      key: cloudnative-pg
