---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name bitmagnet-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        POSTGRES_USER: &dbUser "{{ .pg_user }}"
        POSTGRES_PASSWORD: &dbPass "{{ .pg_pass }}"
        POSTGRES_DATABASE: bitmagnet
        TMDB_API_KEY: "{{ .tmdb_token }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: bitmagnet
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pg_pass }}"
  dataFrom:
  - extract:
      key: bitmagnet
  - extract:
      key: cloudnative-pg
  - extract:
      key: tmdb
