---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secrets
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # Authentik
        AUTHENTIK_SECRET_KEY: "{{ .secret_key }}"
        AUTHENTIK_POSTGRESQL__USER: &dbUser "{{ .pg_user }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbPass "{{ .pg_pass }}"
        AUTHENTIK_POSTGRESQL__HOST: postgres-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbname authentik
        AUTHENTIK_EMAIL__USERNAME: "{{ .email_user }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .email_pass }}"
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .bootstrap_email }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .bootstrap_pass }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .authentik_token }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pg_pass }}"
  dataFrom:
  - extract:
      key: authentik
  - extract:
      key: cloudnative-pg
