---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cluster-user-auth
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # Admin User
        username: "{{ .adminUser }}"
        password: "{{ .pass_enc }}"
  dataFrom:
  - extract:
      key: weave
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name oidc-auth
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # Authentik
        clientID: "{{ .client_id }}"
        clientSecret: "{{ .client_secret }}"
        issuerURL: https://authentik.${SECRET_DOMAIN}/application/o/gitops/
        redirectURL: https://gitops.${SECRET_DOMAIN}/oauth2/callback
        customScopes: openid,profile,email
        claimGroups: groups
        claimUsername: preferred_username
  dataFrom:
  - extract:
      key: weave
