---
libraries:
  Movies:
    collections_files:
      - repo: Movies.yml
      - repo: Movies - Holidays by Drazzizzi.yml
      - repo: Movies - Trakt (Unplayed) by Magic815.yml
      - pmm: basic
      - pmm: imdb
    overlay_files:
      - remove_overlays: false
      - repo: Movies - Overlays - Charts.yml
      - repo: Movies - Overlays - Oscars.yml
      - repo: Movies - Overlays - Ratings.yml
      - repo: Movies - Overlays - Stand-up.yml
      - repo: Movies - Overlays - Streaming Services.yml
      - repo: Movies - Overlays - Studios.yml
    operations:
      mass_genre_update: imdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb

  TV Shows:
    metadata_files:
      - repo: TV Shows.yml
      - pmm: basic
      - pmm: imdb
    overlay_files:
      - remove_overlays: false
      - repo: TV Shows - Overlays - Charts.yml
      - repo: TV Shows - Overlays - Networks.yml
      - repo: TV Shows - Overlays - Ratings.yml
      - repo: TV Shows - Overlays - Statuses.yml
      - repo: TV Shows - Overlays - Streaming Services.yml
      - repo: TV Shows - Overlays - Studios.yml
    operations:
      mass_genre_update: tmdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb
      mass_episode_audience_rating_update: mdb_tomatoesaudience
      mass_episode_critic_rating_update: mdb_metacritic
      mass_episode_user_rating_update: imdb

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  missing_path: config/missing
  only_filter_missing: false
  show_unmanaged: false
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_user:
  playlist_report: false
  verify_ssl: true
  custom_repo: https://github.com/tparker00/k3s-home/tree/main/kubernetes/apps/media/plex/plex-meta-manager/custom/
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users:

plex:
  url: http://plex.media.svc.cluster.local:32400
  token: {{ .plex_token }}
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: true

tautulli:
  url: http://tautulli.media.svc.cluster.local:8181
  apikey: {{ .tautulli_token }}

radarr:
  url: http://radarr-app.downloads.svc.cluster.local
  token: {{ .radarr_token }}
  add_missing: false
  add_existing: false
  root_folder_path: /data/movies
  monitor: true
  availability: announced
  quality_profile: HD - 720p/1080p
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false

sonarr:
  url: http://sonarr-app.downloads.svc.cluster.local
  token: {{ .sonarr_token }}
  add_missing: false
  add_existing: false
  root_folder_path: /data/tv
  monitor: all
  quality_profile: HD - 720p/1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false

tmdb:
  apikey: {{ .tmdb_token }}
  language: en
  cache_expiration: 60
  region:

trakt:
  client_id: {{ .trakt_client_id }}
  client_secret: {{ .trakt_client_secret }}
  authorization:
    access_token: {{ .trakt_access_token }}
    token_type: Bearer
    expires_in: {{ .trakt_expires_in }}
    refresh_token: {{ .trakt_refresh_token }}
    scope: public
    created_at: {{ .trakt_created_at }}
  pin:

mdblist:
  apikey: {{ .mdblist_token }}
  cache_expiration: 60

omdb:
  apikey: {{ .omdb_token }}
  cache_expiration: 60
