---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./moosefs-csi/ks.yaml
  - ./minio/ks.yaml
  - ./restic/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./mounts/ks.yaml
